doc/general/new_source_file.F90

The link appearing between angle brackets is interpreted as a comment by doxygen.

GPL URL does not show up in doxygen docs

---

python/piernik_setup.py

The  compilation of version.F90 fails when the commit messages have double quotes.
```
Error: Empty set of digits in BOZ constant at (1)
```
This can happen for example when you use `git revert` to revert previous commits. Replacing double quotes by escaped characters `\"` in the version.F90 file does not seem to work either.

remove double quotes in recent history using sed

---

src/base/coriolis.F90

Indexes for mass and momentum densities are in the wrong order in the coriolis module. However there is some other bug because this does not help in the advection test to get some deflection for the cartesian coordinates setup.

correct order of array of indexes in coriolis module

---

src/fluids/ionized/initionized.F90

I think this should be defined as `.false.`

[initionized] Fix definition of is_magnetized logical variable

---

src/fluids/ionized/initionized.F90

PR #140 exposed a bug which I apparently missed during review. There's no directive *MAGNETIZED*

Use proper cpp directive for setting fluid magnetization (MAGNETIC)

---

src/base/coriolis.F90

Use the right index for the y sweep in the Coriolis accelration as explained by @Xarthisius in #137.

correct y component acceleration in Coriolis module

---

problems/advection_test/restart_test_v2_jenkins.sh

One test was failing, because it was picking "wrong" *yt* version on build box

Fix PYTHONPATH

---

src/base/units.F90

The ≈ charachter makes the pdflatex compilation of the doxygen latex source to fail.

Use HTML character recognized by doxygen

---

doc/general/main.F90

The `doc/papers` subdirectory is no longer available.

Remove reference to papers subdirectory

---

src/base/non_inertial.F90

We want to successfully compile the code even if VERBOSE

fix use printinfo in non_inertial

---

src/magnetic/resist/resistivity.F90

This should fix FPE occuring in otvorte4x and tearing when FPE exceptions are trapped.

[resistivity] fix for spurious FPE

---

src/base/initpiernik.F90
src/base/piernik.F90

This was caused by early use of timer module which implied calling MPI_Wtime() before MPI_Init()

Fixed 'Attempting to use an MPI routine before initializing MPICH'

---

src/base/constants.F90

little fixup to #197 (the field was effectively named "magnetic_field_d").

fix the problem with truncation of datafield name

---

src/IO/hdf5/common_hdf5.F90

small mistake, visible in newest HDH5 library editions

HDF5 type fix

---

src/fluids/cosmicrays/crhelpers.F90

The pointers to cg in crhelpers need not be intent inout because cg won't change, just some of the content pointed by cg interiors.

cg need not be intent inout in most cases

---

src/IO/hdf5/restart_hdf5_v1.F90
src/IO/hdf5/restart_hdf5_v2.F90

[restart_hdf5_v1,2] fix incorrectly read run_id from restart files, save new_id from the problem.par file

reclaim the functionality of the new_id parameter

---

src/IO/hdf5/common_hdf5.F90

fix counting vars, e.g. in default kepler run

[common_hdf5] fix counting while writing ener and while ISO

---

jenkins/gold_configs/mcrwind
src/IO/hdf5/restart_hdf5_v1.F90
src/base/global.F90
src/base/timestep.F90
src/fluids/fluidtypes.F90
src/scheme/timestep_retry.F90
src/supernovae/snsources.F90

Change of _gold_ for `mcrwind` is required because we change the way how we retry timesteps and `mcrwind` is using this way too much.

Timestep growth and retry changes

---

src/base/finalizepiernik.F90

dfftw_cleanup should not be called before all dfftw_destroy_plan are called
This perhaps fixes problem observed in 8348762f

BUGFIX: dfftw_cleanup moved a bit

---

src/IO/hdf5/restart_hdf5_v1.F90
src/IO/hdf5/restart_hdf5_v2.F90
src/base/constants.F90
src/base/named_array_list.F90
src/grid/cg_list_global.F90
src/scheme/timestep_retry.F90

The `restart_mode` was overloaded a bit to distinguish between *fields that don't need to be put into restart and thus don't need to be backed up for timestep retry* and *fields that are back up of other fields and should never be backed up, under any circumstances*.

Separate mark for fields that serve as a backup

---

src/gravity/pcg.F90
src/grid/decomposition.F90
src/grid/grid_container.F90
src/grid/refinement.F90

Setting AMR_bsize(3) <= 1 in 2D (X-Y) setups was causing wrong decompositions and crashes.

[refinement] BUGFIX for weird 2D decompositions

---

problems/maclaurin/initproblem.F90
problems/maclaurin/problem.par.quite_accurate
src/base/problem_pub.F90
src/base/user_hooks.F90
src/gravity/multigridmultipole.F90
src/multigrid/multigrid_vstats.F90

* Removed ugly #ifdef MACLAURIN_PROBLEM .
* Added `user_hooks::ext_bnd_potential` for bypassing default multipole solver.

Maclaurin unhacking

---

problems/maclaurin/mpi_test.par
src/gravity/multigrid_gravity.F90
src/gravity/multigridmultipole.F90
src/gravity/multipole_array.F90
src/grid/cg_level_connected.F90

Continuation of #317 
* Some small manual optimisations
* Added 3D multipole solver that can be used on coarsened levels for quite accurate results and allows to use only one pass of multigrid for isolated boundaries.

3D multipole solver

---

src/gravity/multigrid_gravity.F90

explicitly set up the potential for an empty space (relevant for some particle setups)

[multigrid_gravity] BUGFIX for an empty space

---

problems/mcrtest/problem.par.build2
src/base/global.F90
src/base/timestep.F90
src/fluids/cosmicrays/initcosmicrays.F90
src/fluids/sources.F90
src/scheme/Riemann_Solver/solve_cg.F90

Allow user to decide:
* whether to use_smalld, use_smallei, use_smallecr,
* whether to repeat step if negatives in density, internal energy density or CR energy density are detected.
These functionalities are available in both schemes: RTVD and RIEMANN.

Keep non negative dens

---

src/fluids/interactions/timestepinteractions.F90
src/fluids/thermal/timestepthermal.F90

Removed global reductions from routines called once per cg

timestep deadlock

---

src/base/timestep.F90
src/fargo/fargo.F90
src/fluids/cosmicrays/initcosmicrays.F90
src/fluids/cosmicrays/timestepcosmicrays.F90
src/fluids/interactions/timestepinteractions.F90
src/fluids/sources.F90
src/fluids/thermal/timestepthermal.F90
src/magnetic/resist/resistivity.F90

Make routines limiting dt independent of cg to be able to reduce individual dt ingredients over processes in case of following them in log files

Timestep routines cg-independent

---

doc/Doxyfile.stable
doc/general/precompiler.F90
piernik.doxy
python/piernik_setup.py
src/gravity/multigrid_gravity.F90
src/gravity/multigrid_gravity_helper.F90

Use -d NO_FFT during setup to force multigrid to not use any FFTW calls.

NO_FFT: FFTW-less multigrid

---

src/gravity/multigrid_gravity.F90

Sometimes badly looking nonconvergence may be caused by inaccuracies of temporal extrapolation right after refinement update

Don't give up in 1st V-cycle 

---

src/IO/hdf5/data_hdf5.F90

* save cancellation of plot vars during the simulation run
* do not process already-cancelled plot var
* do not create h5 description for cancelled plot vars

Non-existent plot vars treatment

---

src/gravity/multigrid_old_soln.F90

It restores repeatability with selfgravity and `ord_time_extrap` = 2

BUGFIX for restarts

---

src/IO/hdf5/data_hdf5.F90
src/grid/refinement.F90
src/grid/refinement/unified_ref_crit_geometrical.F90
src/grid/refinement/unified_ref_crit_geometrical_box.F90
src/grid/refinement/unified_ref_crit_geometrical_point.F90
src/grid/refinement/unified_ref_crit_geometrical_zcyl.F90
src/grid/refinement/unified_ref_crit_list.F90
src/grid/refinement_flag.F90

Implemented a refinement that can mark a cylinder with the axis along Z-direction and independent X- and Y- semiaxes. Similar to refine_boxes but less grid gets refined.

Cylindrical refinement

---

compilers/h5pfc_gnu.in

[compilers/h5pfc_gnu.in] ignore argument mismatch in mpisetup while compiling with gcc10

fix for gcc10

---

src/base/timestep.F90
src/gravity/multigrid_gravity.F90
src/gravity/multigridmultipole.F90
src/grid/cg_leaves.F90
src/grid/cg_level_base.F90
src/grid/cg_level_connected.F90
src/grid/find_level.F90
src/multigrid/multigrid.F90
src/scheme/rtvd_split/solve_cg_rtvd.F90

There was a workaround for years due to circular dependency through `cg_level_base::expand`. Now it should be possible to use `base%level` everywhere instead.

Remove cg_level_connected::base_level

---

src/base/timestep.F90
src/gravity/multigrid_gravity.F90
src/gravity/multigridmultipole.F90
src/grid/cg_leaves.F90
src/grid/cg_level_base.F90
src/grid/cg_level_connected.F90
src/grid/cg_list_bnd.F90
src/grid/find_level.F90
src/grid/grid_container_prolong.F90
src/multigrid/multigrid.F90
src/scheme/rtvd_split/solve_cg_rtvd.F90

It looks like `prolong_bnd_from_coarser` was very inefficient in AMR simulations due to incomplete rank-4 implementation (with workaround through `cg%wa`).
A bit more direct approach (still component-wise) resulted in factor of 2 speedup of a 3D sedov problem with 3 levels of refinemet.
There is another big factor to gain in optimizing the way of calculating fine guardcells over coarse boundary. Some easy gains were done in eaf63af but real improvement will be easier to achieve with MPI-2 communication.

Faster arr4d boundaries

---

bin/qa.py
compilers/lothlorien.in
compilers/tests/mpi.F90
compilers/tests/mpi_allgatherv_bug.F90
compilers/tests/mpi_f08.F90
problems/wt4/initproblem.F90
python/piernik_setup.py
src/IO/dataio.F90
src/IO/hdf5/cg_particles_io.F90
src/IO/hdf5/common_hdf5.F90
src/IO/hdf5/data_hdf5.F90
src/IO/hdf5/restart_hdf5_v2.F90
src/base/cmp_1D_mpi.F90
src/base/defines.c
src/base/mass_defect.F90
src/base/mpisetup.F90
src/base/piernik.h
src/base/ppp_eventlist.F90
src/base/ppp_mpi.F90
src/base/timer.F90
src/grid/cg_level_connected.F90
src/grid/cg_list_balance.F90
src/grid/cg_list_bnd.F90
src/grid/cg_list_dataop.F90
src/grid/cg_list_rebalance.F90
src/grid/dot.F90
src/grid/refinement_update.F90
src/multigrid/multigrid.F90
src/particles/particle_utils.F90
src/scheme/sweeps.F90

* Implemented `FORBID_F08` symbol to enforce older Fortran interface. Can be used dureing setup call (also via `.setuprc`) or in compiler configuration.
* Implemented compatibility with MPI implementations that does bot provide functions such as `MPI_Send` for import in the old fortran interface.

Switchable MPI

---

src/base/global.F90
src/base/mpisetup.F90
src/base/ppp_eventlist.F90
src/base/ppp_mpi.F90
src/grid/cg_level_connected.F90
src/grid/cg_list_bnd.F90
src/grid/cg_list_rebalance.F90
src/grid/dot.F90
src/grid/refinement_update.F90
src/scheme/sweeps.F90

Fighting deadlocks on Tryton:
* Optional MPI_Barriers to enforce "epoch" separation.
* Separate MPI communicator for sepate communication contexts.

Preventing MPI data races

---

src/base/timestep.F90
src/fluids/cosmicrays/cresp_grid.F90
src/fluids/cosmicrays/timestep_cresp.F90

Reduce cfl_cresp_violation across all grids, remove redundant timestep-related instructions.

CFL violation handling for CRESP

---

problems/mcrtest/mcrtest_cresp/initproblem.F90
src/IO/hdf5/common_hdf5.F90
src/fluids/cosmicrays/initcrspectrum.F90

In mcrtest_cresp test problem, when setting ncre = 0, the module is switched off and is not being initialized. In mcrtest_cresp problem file, initproblem.F90, a check for 'use_cresp' was overlooked which resulted in segmentation fault. This is fixed by importing 'use_cresp' and checking it during initialization.

Fix SIGSEGV in initproblem for mcrtest_cresp

---

jenkins/gold_configs/mcrwind.config
problems/mcrwind/problem.par.build
src/base/global.F90
src/base/piernik.F90
src/base/timestep.F90
src/scheme/timestep_retry.F90
src/supernovae/snsources.F90

cfl_violation fix for static conditions with unexpected source added by user
and further development for repeating steps scenarios:
* suspend calling time_step while step is repeated
* control dt shrinking by dt_cur_shrink variable
* new experimental scenario flex that takes precise dt shrinking in just one step repetition attempt
* rename variables to have code better readable

CFL_warn fix

---

src/IO/hdf5/restart_hdf5_v1.F90
src/IO/hdf5/restart_hdf5_v2.F90
src/fluids/cosmicrays/initcrspectrum.F90

If compiled, CRESP is by default switched on. Switching it off is possible via setting ncre to 0 or declaring use_cresp = .false.; it can additionally be partially switched off via use_cresp_evol = .false. (e.g. module and spectrum initialized and spatially propagated, but not spectrally evolved). If use_cresp = .false. the module should not be initialized and no related action should be taken.
This PR disallows use_cresp_evol and reading solution maps (used in the module) from restart file in such case.

Organize CRESP flags and solution map reading from restart.

---

src/IO/dataio.F90
src/IO/dataio_pub.F90
src/IO/hdf5/common_hdf5.F90
src/IO/hdf5/data_hdf5.F90
src/IO/hdf5/io_debug.F90
src/IO/hdf5/restart_hdf5.F90
src/base/initpiernik.F90
src/fluids/cosmicrays/cresp_grid.F90
src/fluids/cosmicrays/multigrid_diffusion.F90
src/particles/particle_pub.F90
src/scheme/fluidupdate.F90
visual/plot_compose.py
visual/plot_utils.py
visual/pvf_settings.py
visual/read_dataset.py

fixups:
* print current time while dumping hdf or res via msg
* reduce code lines to summarize hdf dumps
* multiple_h5files to work again
* use the one routine to find file names
* visualize grid-only and using logscales
* cbar label includes log
* previously hardcoded fineqv moved to pvf_settings

Fixups and cosmetics

---

python/crs_h5.py
src/fluids/cosmicrays/cresp_crspectrum.F90
src/fluids/cosmicrays/initcrspectrum.F90

After the list of active bins is constructed and lists of distribution function f with slope q are computed, assume zero where the bins are inactive in order to avoid flux problems. 
Additionally add 'cresp_disallow_negatives' switch (by default .true. - CFL checks and actions performed); if set to .false. it triggers tolerance of negative values of number density n and energy density e, appearing within CRESP and preventing part of 
CFL violation actions to be taken in that case; these errors are normally fixed via use_smallecr.

CRESP: active bins fixes, option to allow negatives

---

src/base/global.F90
src/base/piernik.F90
src/base/repeatstep.F90
src/base/timestep.F90
src/scheme/timestep_retry.F90
src/supernovae/snsources.F90

This fixes problems (hanging up) occuring on some larger simulations in which repetitive_steps are not allowed. 
Due to possible CFL violation 'repeat_step' flag was being triggered and in setups without repetitive steps, left unattended, this later causes the simulation to stall during an attempt to reduce chspeed (hdc:update_chspeed).

timestep: override repeat_step to false in simulations without repetitve_steps

---

visual/plot_compose.py
visual/plot_utils.py
visual/pvf.py
visual/pvf_settings.py
visual/read_dataset.py

Improvemetns enable:
* comparing files with the same domains but divided into different block structure
* reconstruction of uniform grid for framed blocks of any refinement level
* zooming to refinement level area passed by --zoom LEVEL
* comparing different refinement levels from different file provided that got meshes that matches
* 1d hybrid plots of grid datafield and particles histrogram
* usage of --scale and -z/--zlim  for 1d particles histogram
* introduced -T/--particle-h2d-scale option to mange colorscale for 2d particle histogram separately
* user managing labels of dimensionless units
* print true values instead of symmin-coded to colorbar labels while using symlog scale type

PVF comparison between different levels and other improvements

---

problems/jeans/initproblem.F90
problems/jeans/problem.par.big_domain
problems/jeans/problem.par.dirichlet
problems/jeans/problem.par.small_domain
problems/maclaurin/initproblem.F90
problems/maclaurin/problem.par.big_domain
problems/maclaurin/problem.par.small_domain
problems/sedov/MHD_blast_wave/problem.par.big_domain
problems/sedov/MHD_blast_wave/problem.par.small_domain
problems/sedov/problem.par.big_domain
problems/sedov/problem.par.small_domain
src/IO/dataio.F90
src/base/constants.F90
src/base/func.F90
src/base/piernik.F90
src/fluids/cosmicrays/timestep_cresp.F90
src/fluids/cosmicrays/timestepcosmicrays.F90
src/fluids/interactions/timestepinteractions.F90
src/gravity/multigrid_gravity.F90
src/gravity/multigridmultipole.F90
src/gravity/multipole_array.F90
src/grid/grid_container_base.F90
src/grid/refinement/unified_ref_crit_var.F90
src/multigrid/multigrid_Laplace4M.F90
src/particles/particle_gravity.F90
src/particles/particle_timestep.F90
src/particles/particle_utils.F90

Remove computational faults when the cell sizes are extremely small or extremely big (like when one sets up a galaxy measured in centimeters).
These faults usually result from use of `small` and `big` values from `constants` module. In principle `small` and `big` should prevent division by zero or numerical overflows in single-precision data output but in many places we may safelyuse full range of double precision and avoid biased calculations.

Tiny and huge domains

---

problems/jeans/initproblem.F90
problems/jeans/problem.par.big_domain
problems/jeans/problem.par.dirichlet
problems/maclaurin/initproblem.F90
problems/maclaurin/problem.par.big_domain
problems/sedov/MHD_blast_wave/problem.par.big_domain
problems/sedov/problem.par.big_domain
src/base/constants.F90
src/fluids/interactions/timestepinteractions.F90
src/gravity/multigrid_gravity.F90
src/multigrid/multigrid_Laplace4M.F90

Remove computational faults when the cell sizes are big or extreme (like when one sets up a galaxy measured in centimeters).
These faults usually result from use of small and big values from constants module. In principle small and big should prevent division by zero or numerical overflows in single-precision data output but in many places we may safely use full range of double precision and avoid biased calculations.

Huge domain

---

src/grid/domain.F90
src/grid/grid_container_prolong.F90

It seems that `-Wmaybe-uninitialized` in gfortran 12.x is alittle bit overreacting and throwing false-positives sometimes.
The fixes here are achieved by rearranging the code.

make gfortran 12.x a little bit happier

---

bin/gdf_distance

Treat position, velocity and acceleration components in particle data as 3-vectors by default, similarly to the field data.
This prevents inducing big error norm from a small differences on a near-zero component.

gdf_distance improvement for particles

---

problems/mcrtest/initproblem.F90
src/IO/dataio.F90
src/fluids/cosmicrays/sourcecosmicrays.F90
src/gravity/multigrid_gravity.F90
src/grid/decomposition.F90
src/grid/grid_container_base.F90
src/grid/ordering.F90
src/grid/refinement.F90
src/multigrid/multigrid.F90
src/scheme/Riemann_Solver/hdc.F90
src/supernovae/snsources.F90

An attempt to remove obstacles when the simulation is 0-dimensional (consists of single cell).
Such config may be useful for fast evolving CR spectrum, cooling prescriptions or even particles.
Typical pitfalls are:
* Division by zero: `1 / dom%eff_dim`.
* Uninitialized values: `product(something(:), mask = dom%has_dir(:))`.
* Precomputing dimension-dependent parameters for routines that are called only for existing dimensions.
* Unexpected logical flaws :-)
It is strongly recommended to use `F90FLAGS +=  -ffpe-trap=invalid,zero,overflow` when you test 0-dimensional setups. It may help to spot problematic places.
In order to make Piernik compatible with 0-dimensional setups we need to create a new Jenkins test that will do something sensible. Without that we may easily overlook something.

0-dimensional simulations

---

src/fluids/cosmicrays/cresp_NR_method.F90
src/fluids/cosmicrays/cresp_helpers.F90
src/fluids/cosmicrays/initcosmicrays.F90
src/fluids/cosmicrays/initcrspectrum.F90

* automatically switch off cresp for no spectral CR species selected
* routines to identify CR species by component number

manage indexes for CR spectral

---

src/base/initpiernik.F90

This is a guess that should also work correctly for particles in AMR (but needs checking, once we implement it).

skip double multigrid call when NBODY is defined

---

src/base/initpiernik.F90
src/base/named_array_list.F90
src/fluids/cosmicrays/cr_data.F90
src/gravity/old_soln_list.F90
src/grid/level_essentials.F90
src/grid/load_balance.F90
src/grid/refinement/unified_ref_crit_list.F90
src/magnetic/divB.F90

Apparently Intel compilers do not handle well overwriting a string with itself, which caused the `-n` option to fail to pass commandline parameters.
Some other cases of similar code were also rewritten.

Don't overwrite self

---

src/gravity/multigridmultipole.F90

Should fix the rare case when particles outside the domain were counted twice on some domain decompositions.

[multigridmultipole] don't count particles twice

---

src/IO/dataio.F90
src/IO/hdf5/data_hdf5.F90
src/IO/hdf5/restart_hdf5_v2.F90

[IO] change the default value of nproc_io to 1 as it is usually faster than nproc on NFS.
ToDo: implement general case with the default of 1 thread per node.

[IO] change the default value of nproc_io to 1

---

src/grid/refinement.F90
src/grid/refinement/unified_ref_crit_list.F90
src/grid/refinement/unified_ref_crit_nbody.F90

Requires full compatibility with AMR:
* Creation and destruction on refined grids.
* Transport through fine/coarse boundaries.
* Prolongation and restriction (partnt-child transport) on refinement/derefinement events.
These aspects, or at least some subset of them, should be achieved in #532.

implementation of refinement criterion based on number of particles in cg

---

benchmarking/problem.par.crtest
benchmarking/problem.par.maclaurin
src/base/global.F90
src/fluids/cosmicrays/crdiffusion.F90
src/grid/cg_list_balance.F90
src/grid/cg_list_bnd.F90

Fixed problems with use of `internal_boundaries_MPI_merged` in setups with CR diffusion.
Fixed problem with benchmarking.

Crdiffusion and benchmarking fixups

---

src/base/cnt_array.F90
src/base/global.F90
src/base/log_bins.F90
src/base/mpi/ppp_mpi.F90
src/base/mpi/req_array.F90
src/base/mpi/wrapper_stats.F90

Implemented `waitall_timeout` parameter. If it is set to positive amount of seconds, then Piernik will call MPI_Test* routines instead of MPI_Waitall and after the time expires will print unfinished transactions and Abort execution.
Can be useful for debugging deadlicks.

Adding a timeout and some diagnostics to MPI_Waitall wrapper

---

bin/qa.py
jenkins/gold_configs/mcrtest_CRESP.config
problems/fargo_test/initproblem.F90
problems/streaming_global/initproblem.F90
src/IO/hdf5/common_hdf5.F90
src/IO/hdf5/data_hdf5.F90
src/IO/hdf5/restart_hdf5_v1.F90
src/IO/hdf5/restart_hdf5_v2.F90
src/base/func.F90
src/base/named_array_list.F90
src/fluids/cosmicrays/multigrid_diffusion.F90
src/grid/cg_level_connected.F90
src/grid/cg_list_bnd.F90
src/grid/cg_list_dataop.F90
src/grid/cg_list_global.F90
src/grid/grid_container_na.F90
src/grid/rebalance.F90
src/multigrid/multigrid_vstats.F90
src/scheme/timestep_retry.F90

The types defined in `named_array_list` can also hold the names of individual fields in case of rank-4 arrays (such as `cg%w`. This should make it easier to handle the multitude of CR species.

Field names in named_array_list

---

src/base/timestep.F90

explore information about unwanted negatives in a proper order

rearrange calls in check_cfl_violation

---

jenkins/gold_configs/mcrtest_CRESP.config
src/fluids/cosmicrays/cresp_NR_method.F90

Some use of uninitialized value were caught and fixed. This explains compiler-dependent behavior and dependence on apparently unrelated compiler flags.

Fix for CRESP nonconvergence

---

jenkins/gold_configs/MHDsedovAMR.config
src/scheme/Riemann_Solver/hdc.F90

This should fix the problem with `MHDsedovAMR` gold test failing under heavy load.
The problem occured when a single thread got no cg to process after reshuffle and `ch_grid` was .true. (the default value).
Depleting a thread can occur when the code detects a particularly slow thread lagging behind other threads.

Chspeed fixup
