compilers/della4.in
Compiler flags used for Piernik on della4 machine:
http://www.princeton.edu/researchcomputing/computational-hardware/machine-2/
=> compiler flags for della4

doc/general/main.F90
Remove reference to lecture notes and PDF slides.
=> [docs] lecture notes and slides are not available in git repo

python/DirWalk.py, python/piernik_setup.py
These changes add support for python 3 in the piernik_setup script. This version also works well with python version 2.7 that is required by Piernik.
=> Python 3 support

problems/roche/initproblem.F90
I think that the x and y coordinates were swapped in the initial conditions routine.
=> [roche] fix initial problem conditions

src/base/units.F90
Added new unit system for simulations of binary systems (AU, Msun, yr).
=> New unit system for binary systems

problems/advection_test/initproblem.F90, problems/advection_test/piernik.def, problems/advection_test/problem.par, problems/advection_test/problem.par.cylindrical, problems/advection_test/problem.par.rotating, src/base/initpiernik.F90, src/base/non_inertial.F90, src/scheme/rtvd_split/rtvd.F90
The goal of this module is to define the fictitious forces in a rotating frame to be included in the RTVD solver.
=> Module for non-inertial forces

problems/wind/info, problems/wind/initproblem.F90, problems/wind/piernik.def, problems/wind/problem.par
This is a new problem .for a binary wind accreting stellar system where the primary star is an evolved star with a strong wind.
=> Wind accretion problem setup

problems/override_test/info, problems/override_test/initproblem.F90, problems/override_test/piernik.F90, problems/override_test/piernik.def, python/piernik_setup.py
Implemented a simple mechanism that allows for reimplementation of main Piernik files from user problem without disturbing main source tree. Use wisely.
=> File override

src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/data_hdf5.F90, src/IO/hdf5/grid_data_format.F90, src/IO/hdf5/helpers_hdf5.F90, src/base/constants.F90, src/base/units.F90
**This is still "work in progress" so please don't merge**
Adds support for native units in GDF (and therefore in yt-3.x). Testers are welcome :)
=> [WIP] GDF  v1.1

python/piernik_setup.py
This works with python 3 and 2.7
=> convert bytes object to string

doc/Doxyfile.stable
Tags `SYMBOL_CACHE_SIZE` `XML_SCHEMA` and `XML_DTD` have become obsolete.
=> update doxygen configuration file

doc/Doxyfile.stable
=> Revert recent changes to doc/Doxyfile.stable

python/yt_ray.py
IMO very useful for gnuplot fans.
=> A tool for taking 1D samples along a line

src/IO/dataio.F90, src/base/non_inertial.F90, src/grid/cg_list_dataop.F90
Properly write min(vely)&co to log files (fix to the commit 787e8b1378ad27f58e79e5c56fd2dee65c9a7938)
=> Fix geoxyz logs

src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/data_hdf5.F90, src/base/constants.F90, src/base/units.F90
energy units and gdf name translations were confusing - fixing that for gas and cosmic rays
=> Fix energy units

src/base/initpiernik.F90
Reading commandline now should be a bit safer.
=> Cmdline fix

src/IO/dataio_pub.F90, src/base/initpiernik.F90
Some log lines were missing, some were duplicated, non-master processes could silently log to nowhere.
Now it should be fixed.
=> Fix missing log lines

src/IO/hdf5/data_hdf5.F90
added face- and cell-centered formulas for dumping div(B) straight to te output files
=> div(B) in .h5 plotfiles

problems/blob/initproblem.F90, problems/blob/problem.par, problems/blob/problem.par.wt3_hi, problems/blob/problem.par.wt3_med, src/base/initpiernik.F90, src/base/user_hooks.F90
Now it should be possible to use the original initial conditions that are provided on Astrosim page.
=> Wengen Test 3 

problems/2D_RIEMANN/initproblem.F90, problems/2D_RIEMANN/problem.par, problems/otvortex/initproblem.F90, problems/sedov/initproblem.F90, problems/sedov/problem.par.magnetized_2D, problems/shock1d_rj/how_to_run_in_y_or_z_direction, problems/shock1d_rj/initproblem.F90, problems/shock1d_rj/problem.par.rj1a, problems/shock1d_rj/problem.par.rj1b, problems/shock1d_rj/problem.par.rj2a, problems/shock1d_rj/problem.par.rj2b, problems/shock1d_rj/problem.par.rj3a, problems/shock1d_rj/problem.par.rj3b, problems/shock1d_rj/problem.par.rj4a, problems/shock1d_rj/problem.par.rj4b, problems/shock1d_rj/problem.par.rj4c, problems/shock1d_rj/problem.par.rj4d, problems/shock1d_rj/problem.par.sod
Selection of cherrypicked commits from dev_riemann that aren't strictly related to the Riemann solver
=> Some problem fixups

compilers/gnu47.in, src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/data_hdf5.F90
some more bits cherrypicked mostly from dev_riemann branch before merge of the riemann solver
=> Small addons and fixups

.gitignore, piernik.doxy, src/fluids/fluxes.F90
small adjustments for Doxygen documentation
=> Doxy fixups

problems/mandelbrot/initproblem.F90, problems/mandelbrot/problem.par.polar, problems/mandelbrot/problem.par.polar.1-2-3-4-5-6, problems/mandelbrot/problem.par.polar.3-3-3-3-3-3, problems/mandelbrot/problem.par.polar.3x3x3x3x3x3, problems/mandelbrot/problem.par.polar.FM, problems/mandelbrot/problem.par.zoom_1, problems/mandelbrot/problem.par.zoom_2, problems/mandelbrot/problem.par.zoom_3, problems/mandelbrot/problem.par.zoom_4
Added a feature for polar views around selected point (with logarithmic radial scale) and some example parameter files. Recommend Volcano colormap (Hardcandy seem to work well too) for yt plot.
The Mandelbrot problem is intended for stress testing of the AMR subsystem. There are more efficient fractal generators around :-)
=> Polar mandelbrot

src/IO/hdf5/data_hdf5.F90
Added cell-centered and face-centered 4-th and 6-th order estimators of div(B), available as `divbc4`, `divbf4`, `divbc6` and `divbf6`.
=> Highorder div b

problems/advection_test/initproblem.F90, problems/advection_test/problem.par.divB_test
The `advection_test` was expanded to allow for some simple checks of div B preservation.
=> Advection div b

problems/crwind/initproblem.F90, problems/lingrav/initproblem.F90, problems/mcrwind/initproblem.F90, problems/shock1d_rj/initproblem.F90, src/supernovae/snsources.F90
Few more uninitialized variables hidden in problems
=> Problem hidden uninitialized

Makefile
Added useful calls to the Makefile such as QA and PEP8 checks
=> Makefile extras

jenkins/gold_configs/mcrtest_new, jenkins/gold_test.sh, problems/crtest/problem.par.build, problems/divvtest/problem.par, problems/mcrtest/initproblem.F90, problems/mcrtest/problem.par, problems/mcrtest/problem.par.build, problems/mcrtest/problem.par.build2, problems/mcrwind/problem.par.multigrid, problems/mcrwind/problem.par.selfgrav, src/fluids/cosmicrays/multigrid_diffusion.F90
enabled multiple blocks per process in mcrtest
=> CR problems improvements

problems/fargo_test/initproblem.F90, problems/streaming_global/initproblem.F90, src/base/constants.F90, src/base/named_array_list.F90, src/grid/cg_list_global.F90, src/scheme/rtvd_split/fluidupdate.F90
Let's automagically generate fields for timestep retrying. In principle everything that goes to restart should also be reverted when needed.
=> Auto field step retry

bin/gdf_distance, jenkins/gold_test.sh, python/piernik_setup.py
Few fixes to make Python3 happier
=> Python3isation

src/grid/grid_container.F90
the problem occured for nonexisting directions in 1D and 2D
=> [grid_container] fixed an issue when code complained about too small cells

Makefile, problems/advection_test/initproblem.F90, problems/advection_test/magnetized_advection_test/problem.par.constB, problems/otvortex/piernik.def, src/base/global.F90, src/base/timestep.F90
Minor improvements to some problems, relevant mostly for developers
=> Problems improvements

src/IO/hdf5/data_hdf5.F90
Restore consistency between plotfiles and problem definitions. Important for strong magnetic field.
=> [data_hdf5] bugfix for calculation of pressure in ionized fluid

problems/advection_test/initproblem.F90, src/base/piernik.F90, src/grid/cg_level.F90, src/grid/refinement_update.F90
some fixes to use VERBOSE option
=> Fix verbose

jenkins/gold_configs/mcrwind, problems/crwind/piernik.def, problems/mcrwind/initproblem.F90, problems/mcrwind/piernik.def, src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/restart_hdf5_v1.F90, src/IO/hdf5/restart_hdf5_v2.F90, src/base/finalizepiernik.F90, src/base/initpiernik.F90, src/base/randomization.F90, src/scheme/rtvd_split/fluidupdate.F90, src/supernovae/snsources.F90
changes to manage random seed (important for snsources)
=> Random utils

src/base/global.F90, src/scheme/Riemann_Solver/fluidupdate.F90, src/scheme/Riemann_Solver/hdc.F90
small fixups after merge divclean_RC
=> integer kind corrections

src/grid/grid_container.F90, src/scheme/rtvd_split/rtvd.F90
Geometric factors and index offsets moved from rtvd to grid_container.
=> Simplify amr fluxes

src/scheme/Riemann_Solver/fluidupdate.F90, src/scheme/Riemann_Solver/fluxlimiters.F90, src/scheme/Riemann_Solver/hlld.F90, src/scheme/Riemann_Solver/interpolations.F90
Transposed 1D Rieman solver, interpolations and limiters. Should be both faster than previous version and more compatible with RTVD.
=> Riemann transposed

bin/gdf_distance, problems/advection_test/magnetized_advection_test/problem.par, problems/advection_test/magnetized_advection_test/problem.par.constB, src/IO/hdf5/data_hdf5.F90, src/base/constants.F90, src/base/global.F90, src/base/named_array_list.F90, src/gravity/gravity.F90, src/gravity/multigridmultipole.F90, src/grid/cg_list_global.F90, src/magnetic/bfc_bcc.F90, src/scheme/Riemann_Solver/hlld.F90, src/scheme/Riemann_Solver/interpolations.F90, src/scheme/Riemann_Solver/solve_cg.F90, src/scheme/fluidupdate.F90, src/scheme/rtvd_split/solve_cg.F90, src/scheme/sweeps.F90
Preparing the Riemann solver to be able to tread source terms (such as gravity) with accuracy consistent with Runge-Kutta scheme.
=> Riemann sources

src/gravity/multigrid_gravity.F90, src/gravity/multigrid_old_soln.F90, src/gravity/old_soln_list.F90, src/scheme/timestep_retry.F90
Current implementation looks like written in BASIC and is hard to manage. Lest's implement it more safely with lists.
=> Multigrid gravity old solution redesign

src/IO/dataio_pub.F90, src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/helpers_hdf5.F90, src/IO/hdf5/restart_hdf5_v2.F90, src/IO/hdf5/set_get_attributes.F90
Implementing easier way of setting attributes in .res and .h5 files.
=> Hdf5 easy attributes

jenkins/gold_configs/mcrwind, problems/crtest/problem.par, problems/crtest/problem.par.build, problems/crtest/problem.par.debug, problems/crtest/problem.par.expanding_domain, problems/divvtest/problem.par, problems/mcrtest/problem.par, problems/mcrtest/problem.par.build, problems/mcrtest/problem.par.build2, problems/mcrwind/problem.par, problems/mcrwind/problem.par.build, problems/mcrwind/problem.par.multigrid, problems/mcrwind/problem.par.multisn_wind, problems/mcrwind/problem.par.selfgrav, problems/mcrwind/problem.par.singlesn_test, src/base/defines.c, src/base/initpiernik.F90, src/base/piernik.h, src/fluids/cosmicrays/initcosmicrays.F90, src/fluids/cosmicrays/timestepcosmicrays.F90, src/scheme/fluidupdate.F90, src/scheme/timestep_retry.F90, src/supernovae/snsources.F90
Misc efforts to keep the code tidy
=> do_simple (misc cosmetics)

src/IO/dataio.F90, src/base/named_array_list.F90, src/fluids/initfluids.F90, src/grid/cg_level_connected.F90, src/grid/cg_list_global.F90, src/grid/grid_container_na.F90, src/scheme/Riemann_Solver/hlld.F90, src/scheme/Riemann_Solver/interpolations.F90, src/scheme/Riemann_Solver/solve_cg.F90, src/scheme/fluxtypes.F90, src/scheme/sweeps.F90
Don't even allocate B field for nonmagnetic problems.
=> Truly nonmagnetic

compilers/lothlorien.in, src/IO/hdf5/restart_hdf5_v2.F90, src/base/constants.F90, src/base/named_array_list.F90, src/fluids/dust/initdust.F90, src/fluids/fluidtypes.F90, src/fluids/fluxes.F90, src/fluids/ionized/initionized.F90, src/fluids/neutral/initneutral.F90, src/grid/grid_container_bnd.F90, src/grid/refinement.F90, src/scheme/fluxtypes.F90
=> Int kind, cosmetics

src/gravity/multigrid_gravity.F90, src/gravity/multigridmultipole.F90, src/gravity/multipole_array.F90
Moved Q(:,:,:) to a separate type to allow for more flexible usage of multipoles.
=> Multipole refactoring

problems/maclaurin/initproblem.F90, problems/maclaurin/problem.par.multipole_3D, src/gravity/multigrid_gravity.F90, src/gravity/multigridmultipole.F90, src/gravity/multipole_array.F90
Make multipole solver more robust and be able to work reliably in wider range of coordinates, also far-far away from the computational domain.
=> [WIP] Distant multipoles

src/base/constants.F90, src/fluids/cosmicrays/crdiffusion.F90
[crdiffusion] wait with multiplying by oneq or half to do it once at the end
=> little optimization in very crowded routine cr_diff

src/IO/dataio_pub.F90
[dataio_pub] switch off asynchronous write to log files - workaround for >=gcc-8
=> temporarily switched off asynchronous write to log files

problems/advection_test/initproblem.F90, problems/analytic_periodic_potential/initproblem.F90, problems/conservation_test/initproblem.F90, problems/maclaurin/initproblem.F90, problems/sedov/MHD_blast_wave/problem.par.AMR, problems/sedov/initproblem.F90, src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/data_hdf5.F90, src/base/piernik.F90, src/grid/cg_list.F90, src/grid/refinement.F90, src/grid/refinement_crit_list.F90, src/grid/refinement_filters.F90, src/grid/refinement_update.F90
Refinement criterion based on 2nd derivative
=> Loechner refinement

src/IO/dataio.F90, src/fluids/cosmicrays/crdiffusion.F90, src/fluids/fluxes.F90, src/fluids/ionized/initionized.F90, src/fluids/sources.F90, src/magnetic/resist/resistivity.F90, src/scheme/ct.F90
fix rarely used setups:
* IONIZED && NONMAGNETIC
* NEUTRAL && MAGNETIC
* COSM_RAYS && !IONIZED && NEUTRAL
* RESISTIVE && !IONIZED
=> CR non-ION fix

src/base/global.F90, src/base/piernik.F90, src/base/timestep.F90, src/fluids/cosmicrays/initcosmicrays.F90, src/fluids/cosmicrays/timestepcosmicrays.F90, src/fluids/sources.F90
* add switch to consider cosmic rays negatives to repeat fluidstep
* pass the information about negatives to warn type cflcontrol
* fix dumping files while cfl_violated due to negatives
=> Fix non-negatives

src/scheme/Riemann_Solver/hdc.F90, src/scheme/Riemann_Solver/hlld.F90, src/scheme/Riemann_Solver/solve_cg.F90
Implementation of isothermal option for the Riemann solver.
=> ISO Riemann

src/scheme/Riemann_Solver/hlld.F90
Bugfix: now dust pressure should always be 0 in the Riemann solver.
=> ISO + Riemann + dust

src/base/initpiernik.F90, src/gravity/hydrostatic.F90
Reorganize and fix hydrostatic routines
=> Fix hydrostatic

problems/blob/problem.par.AMR, problems/dustblob/problem.par.AMR, problems/selfgrav_clump/initproblem.F90, problems/selfgrav_clump/piernik.def, problems/selfgrav_clump/problem.par.AMR, problems/wt4/initproblem.F90, problems/wt4/problem.par.AMR, src/IO/dataio.F90, src/IO/dataio_user.F90, src/IO/hdf5/restart_hdf5.F90, src/base/all_boundaries.F90, src/base/initpiernik.F90, src/fluids/interactions/interactions.F90, src/gravity/multigrid_gravity.F90, src/gravity/multigrid_old_soln.F90, src/gravity/multipole_array.F90, src/grid/cg_leaves.F90, src/grid/refinement_update.F90, src/scheme/Riemann_Solver/hlld.F90
ISO glitches, missing deallocations etc.
=> Various fixups

src/IO/hdf5/data_hdf5.F90
There was a problem with FPE crashes happening in single-precision output.
=> Workaround for nproc > total cg

compilers/gnu47.in, src/base/func.F90, src/base/sortable_list.F90, src/fluids/interactions/interactions.F90, src/gravity/hydrostatic.F90, src/grid/refinement/unified_ref_crit_list.F90, src/grid/sort_cg_list.F90, src/grid/sort_piece_list.F90, src/grid/sort_segment_list.F90
Preparing clean compilation on newest system
=> Fedora31 fixups

bin/extract_problem_par.py, bin/qa.py, make_test.py, python/maclaurin.py, python/yt_ray.py
Let's make our Python scripts ready for Python 2 deprecation.
=> Python3-isation

src/IO/dataio.F90, src/scheme/Riemann_Solver/hdc.F90
The value of chspeed should appear in logfiles (if applicable)
=> c_h speed goes to logfile

src/base/piernik.F90
Let finish the simulation if cfl_violated and we ignore it anyway
=> BUGFIX for infinite timestep loop

src/base/initpiernik.F90, src/gravity/gravity.F90, src/gravity/multigrid_gravity.F90, src/gravity/multigrid_old_soln.F90, src/scheme/fluidupdate.F90
Moved `call source_terms_grav` to be executed right after sweeps.
=> selfgrav after sweeps

problems/advection_test/initproblem.F90, problems/analytic_periodic_potential/initproblem.F90, problems/conservation_test/initproblem.F90, problems/crtest/initproblem.F90, problems/int_bnd_test/initproblem.F90, problems/mandelbrot/initproblem.F90, problems/particle_map_test/initproblem.F90, problems/pr_test/initproblem.F90, problems/therm_inst/initproblem.F90, problems/wt4/initproblem.F90, src/IO/hdf5/io_debug.F90, src/base/cmp_1D_mpi.F90, src/fluids/interactions/interactions.F90, src/grid/cg_level_connected.F90
=> Tardy fixes

INSTALL.md, bin/gdf_distance, jenkins/gold_test.sh, problems/advection_test/restart_test_v2_jenkins.sh, python/read_dataset.py
Remove any dependence on YT from gdf_distance or ay other script used by Jenkins.
=> Yt-free gdf distance

src/grid/refinement/unified_ref_crit_var.F90
Despaghettification as a bonus.
=> [refinement] restored compatibility with old gcc

src/base/global.F90, src/grid/cg_level_connected.F90, src/grid/cg_list_global.F90
experimentally enabled prolongation orders != injection for the fluid
=> ord_fluid_prolong

problems/maclaurin/initproblem.F90, problems/maclaurin/problem.par, problems/maclaurin/problem.par.multipole_3D, problems/wt4/problem.par.AMR, src/gravity/multigrid_gravity.F90, src/gravity/multigridmultipole.F90, src/gravity/multipole_array.F90, src/grid/cg_level_finest.F90, src/multigrid/multigrid.F90, src/multigrid/multigridvars.F90
Some configurations may lead to unnecessarily big array for multipole data. Give more control on multipole accuracy to the user.
=> Multipole 3D optimization

src/grid/refinement/unified_ref_crit_list.F90
Restoring compatibility with ifort.
=> Ifort Fixups

jenkins/gold_configs/mcrtest_new.config, jenkins/gold_configs/mcrwind.config, src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/data_hdf5.F90, src/base/units.F90, src/fluids/cosmicrays/crdiffusion.F90, src/fluids/cosmicrays/crhelpers.F90, src/scheme/fluidupdate.F90
* extend CR dataset names to cr01:cr99
* sFRST, sLAST, sCHNG for make_sweep loop in fluidupdate
* reduce compare_str calls for divvel code
=> reconciliation with cresp branches

jenkins/gold_configs/streaming_instability.config, jenkins/gold_test.sh
small fixes to make gfortran 10.x happier
=> 'make gold' with gfortran 10.x

jenkins/gold_configs/mcrtest_new.config, jenkins/gold_configs/mcrwind.config, jenkins/gold_configs/resist.config, jenkins/gold_configs/streaming_instability.config, jenkins/gold_test.sh
This is the only way to make it working the same way on different machines
=> Upgrade all golds to MPI_F08-ready state

src/base/ppprofiling.F90, src/grid/cg_level_connected.F90, src/grid/cg_list_bnd.F90, src/grid/cg_list_rebalance.F90, src/grid/dot.F90, src/grid/refinement_update.F90, src/scheme/sweeps.F90
Added a PPP wrapper around MPI_Waitall.
=> PPP Waitall

python/piernik_setup.py
Fixed F08 autodetection with --copy option
=> F08 minor fixup

problems/testing_and_debuging/pr_test/initproblem.F90, src/gravity/multigridmultipole.F90, src/grid/cg_level_connected.F90
This should significantly improve the performance in CRESP
=> true rank-4 array restriction

Makefile, visual/plot_compose.py, visual/plot_utils.py, visual/pvf.py
Add visual directory to pycodestyle checks
=> Pycodestyle visual

src/grid/cg_leaves.F90, src/grid/cg_level_connected.F90
Optimized coarse-to-fine prolongation to guardcells in rank-4 arrays.
=> Prolong bnd w

src/base/global.F90, src/base/mpisetup.F90, src/base/ppprofiling.F90, src/grid/cg_list_bnd.F90, src/grid/cg_list_neighbors.F90, src/grid/grid_container_bnd.F90
Some optimisations to internal_boundaries call.
=> Opt internal bnd

problems/testing_and_debuging/pr_test/initproblem.F90, src/base/initpiernik.F90, src/fluids/cosmicrays/multigrid_diffusion.F90, src/gravity/multigrid_gravity_helper.F90, src/grid/cg_level_connected.F90
Some performance gain on refinement creation and updates.
=> true rank-4 array prolongation

src/IO/dataio.F90, src/base/finalizepiernik.F90, src/fluids/cosmicrays/cr_data.F90, src/magnetic/resist/resistivity.F90
Fixups found for some harmless mistakes (valgrind + MPICH + old mpi interface).
=> Valgrinding

src/base/ppp_eventlist.F90, src/base/ppp_events.F90, src/base/ppp_mpi.F90, src/base/ppprofiling.F90, src/grid/cg_level_connected.F90, src/grid/cg_list_bnd.F90, src/grid/cg_list_rebalance.F90, src/grid/dot.F90, src/grid/refinement_update.F90, src/scheme/sweeps.F90
PPP was split into modules, where possible.
Some fixups and simplifications were applied too.
=> PPP modularisation

visual/plot_compose.py, visual/pvf.py, visual/read_dataset.py
Improvements to the PVF:
* Particles scattering included particles-only option
* working with list of files
* scaling plot axes with a physical unit
=> Simple visualization of particles

src/IO/dataio.F90, src/particles/particle_solvers.F90, src/particles/particle_utils.F90
* particle diagnostics file name convention
* fix for tsl data for parallel runs
* restrict calls for particle diagnostics
=> Nbody diagnostics fixes

visual/plot_tsl.py
* fix amount of plots for multi-file and multi-field plots
* fix location and content of the legend
=> fixes for tsl-plotting

src/IO/dataio.F90
* fixing temperature
* stop using smallp in logfile
=> Fix temperature and pressure in logfile

visual/plot_compose.py, visual/plot_utils.py, visual/pvf.py, visual/read_dataset.py
* particles mass 2D histogram
* manage multiple colorbars
* whiten unused axes when colorbars are placed in their field
* option to save file with other formats
=> Particle histogram and PVF improvements

bin/gdb_killall, bin/gdb_wrap
Try to use this to catch the deadlocks.
=> gdb wrapper

.gitignore, python/crs_h5.py, python/interactive_plot_crs.py
Fixes usage of interpolated values of spectral index q and makes it default (thus less faulty), active bin detecting akin to cresp_crspectrum, plotting spectral plots using list of points, PEP8 small aesthetical fixes
=> CRESP: python visualization fixes

bin/gdf_distance
The `gdf_distance` tool now autodetects vectors of data such as velocity, magnetic field and CR components and compares them as vectors, producing single distance value for all components of the mentioned quantities.
=> Vector gdf distance

problems/therm_inst/initproblem.F90, problems/therm_inst/problem.par, src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/data_hdf5.F90, src/base/constants.F90, src/base/defines.c, src/base/finalizepiernik.F90, src/base/units.F90, src/fluids/thermal/thermal.F90
Reduce not necessary computation and conform more the code
=> Cooling more

problems/2body/1particle/initproblem.F90, problems/3body_orig/initproblem.F90, problems/advection_test/initproblem.F90, problems/blob/initproblem.F90, problems/crtest/initproblem.F90, problems/maclaurin/initproblem.F90, problems/mcrtest/initproblem.F90, problems/mcrtest/mcrtest_cresp/initproblem.F90, problems/selfgrav_clump/initproblem.F90, problems/testing_and_debuging/analytic_periodic_potential/initproblem.F90, problems/testing_and_debuging/conservation_test/initproblem.F90, problems/wt4/initproblem.F90, src/IO/hdf5/data_hdf5.F90, src/base/piernik.h, src/fluids/cosmicrays/fluxcosmicrays.F90, src/fluids/dust/initdust.F90, src/fluids/ionized/initionized.F90, src/fluids/neutral/initneutral.F90, src/fluids/tracer/fluxtracer.F90, src/gravity/multigrid_gravity.F90, src/grid/cg_level_connected.F90, src/magnetic/divB.F90, src/multigrid/multigrid_Laplace2.F90, src/multigrid/multigrid_Laplace4M.F90, src/multigrid/multigrid_helpers.F90
Make sure that user puts values into cg blocks within physical area and borders are left for bnd-related activities
=> define default RNG to shortly set values into cg blocks

src/grid/cg_list_bnd.F90, src/grid/domain.F90
[cg_list_bnd,domain] restore vel_outd parameter and use it in BND_OUTD boundary conditions
=> Specify optional vel_outd velocity for BND_OUTD

src/grid/cg_list_bnd.F90, src/grid/domain.F90
* add vel_outd to BASE_DOMAIN namelist
* fix sings and domain sides
* multiply vel_outd by current density
=> fix implementation of velocity limit for OUTD bnd conditions

bin/gdf_distance
count distance for vectors of named fluids like vlxi..vlzi
=> gdf_distance for vectors

visual/plot_compose.py, visual/plot_utils.py, visual/pvf.py, visual/pvf_settings.py, visual/read_dataset.py
Introduce new options:
--compare-datafield VAR to make comparison to VAR datafield
--compare-file to make comparison of a certain datafield from another file
--compare-type to make comparison of different types: difference, ratio or ratio-1
=> PVF option: visual comparison

python/ppp_plot.py
* Added an option to select a subset of processes (useful for browsing massively parallel outputs).
* Added an option to select a time interval so only events overlapping with it are shown.
=> More options for PPP

visual/plot_compose.py, visual/plot_utils.py, visual/pvf.py, visual/read_dataset.py
Add option to find maximum/minimum value in the domain and set center of the plot in that position
=> PVF extrema option

problems/2body/initproblem.F90, problems/2body/piernik.def, src/IO/dataio.F90, src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/data_hdf5.F90, src/IO/hdf5/particles_io.F90, src/IO/hdf5/restart_hdf5_v2.F90, src/base/initpiernik.F90, src/base/piernik.F90, src/base/piernik.h, src/gravity/multigridmultipole.F90, src/particles/particle_diag.F90, src/particles/particle_gravity.F90, src/particles/particle_maps.F90, src/particles/particle_pub.F90, src/particles/particle_solvers.F90, src/particles/particle_timestep.F90, src/particles/particle_types.F90, src/particles/particle_utils.F90, src/particles/star_formation.F90, visual/plot_utils.py
multicg & parallel particles I/O & computation:
* parallel & serial mode for particles I/O
* particles migration across cg blocks in multicg and/or parallel mode
* fixes for tracing particles outside the domain
* fixes for timestep_nbody
* fixes, cleaning and cosmetics
=> particles in multicg

bin/gdf_distance, visual/plot_compose.py
Fixes to:
* gdf_distance longestkey
* particles 1D plots
=> Various fixes

visual/plot_compose.py, visual/plot_utils.py, visual/pvf.py, visual/pvf_settings.py
PVF management of:
* dataset labels next to colorbar
* norm for scale of the colorbar
* formats of colorbar ticklabels
=> PVF management of dataset and cbar labels

src/grid/grid_container.F90, src/grid/grid_container_bseg.F90
... and a fix for SIGSEGV with ifort/ifx.
=> simplified cleanup

jenkins/gold_configs/mcrtest_CRESP.config, src/IO/hdf5/common_hdf5.F90, src/IO/hdf5/data_hdf5.F90
Change cr names : cree, cren to cr_e-e, cr_e-n
=> Change cr names 

src/base/named_array.F90, src/gravity/multigrid_gravity.F90, src/grid/grid_container.F90, src/particles/particle_func.F90, src/particles/particle_gravity.F90, src/particles/particle_maps.F90, src/particles/particle_solvers.F90, src/particles/particle_types.F90, src/particles/particle_utils.F90
Adding PPP calls and per-cg-costs collection related to particles
=> Nbody profiling

src/gravity/multigrid_gravity.F90
This may help for better control on what contributes to the potential when you need to construct something special, not necessarily up-to-date.
=> [multigrid_gravity] added an option to ignore particles in self-gravity

src/gravity/multigrid_gravity.F90, src/grid/refinement_update.F90
* enable use of multigrid in grav_pot_3d
* enable general use of cg%q fields as sources in the multigrid
=> Self-gravity multigrid improvements

problems/maclaurin/initproblem.F90, problems/maclaurin/problem.par.plummer
The Plummer sphere is now available in the `maclaurin` problem.
=> Implemented the Plummer sphere

problems/testing_and_debuging/N-body/info, problems/testing_and_debuging/N-body/initproblem.F90, problems/testing_and_debuging/N-body/piernik.def, problems/testing_and_debuging/N-body/problem.par
This may be a handy setup for tasks like:
* debugging NBODY implementation (I/O, AMR, ...),
* profiling and optimizing NBODY implementation,
* experimenting with load balancing and other technical stuff related to NBODY.
=> A blob made of particles to stress-test particle implementation in Piernik

src/grid/cg_cost.F90, src/grid/grid_container_prolong.F90, src/particles/particle_utils.F90, src/scheme/Riemann_Solver/hlld.F90
* Safer and possibly faster Riemann.
* A bit faster prolong.
=> optimizations

src/IO/dataio.F90, src/IO/hdf5/common_hdf5.F90, src/base/piernik.F90, src/base/procnames.F90, src/grid/cg_leaves.F90, src/grid/cg_level_connected.F90, src/grid/load_balance.F90, src/grid/load_balance_helpers.F90, src/grid/rebalance.F90, src/grid/refinement.F90, src/scheme/Riemann_Solver/fluxlimiters.F90
* `echo refine > msg` – will call rebalance ASAP.
* `/BALANCE/ flexible_balance = .true./` in problem.par should do rebalancing after start, restart and when it detects uneven balance.
* `/BALANCE/ n_rebalance = 5/` will call rebalance every 5 steps (may be useful with particles).
=> Automatic rebalance

benchmarking/README.md, benchmarking/piernik_bench.sh, benchmarking/standard_set_of_tests.sh
Exercised Copilot on shell scripts and Readme of the benchmarking facility of Piernik.
While both natural language and shell script refactoring capabilities are impressive, a lot of attention and careful debugging was required.
* In the `README.md` Copilot insisted on excluding some informations even when it was directly instructed to focus on language clarity, while maintaining all technical details. It also insisted on including plainly false information on setting OMP_NUM_THREADS.
* In the fairly simple `standard_set_of_tests.sh` script all changes looked correct, safe and desired.
* In the more complicated `piernik_bench.sh` the proposed changes were inspiring but not directly applicable. The whole process took few iterations to reach both well-refactored and well-working script. …
=> Benchmarking copilot

src/grid/refinement_update.F90, src/particles/particle_utils.F90
Particle flags need to be updated in order to be properly treated after refinement change.
=> bug fix for particles not following refinements

problems/sedov/problem.par.AMR.threshold_ref, problems/testing_and_debuging/refinement_stress/info, problems/testing_and_debuging/refinement_stress/initproblem.F90, problems/testing_and_debuging/refinement_stress/piernik.def, problems/testing_and_debuging/refinement_stress/problem.par, src/grid/refinement/URC_var.F90
Implemented new mode for refinement – refine when variable > threshold, optionally up to some level.
=> Refine on threshold

benchmarking/piernik_bench.sh
The benchmarking script was expanded to also measure the performance differences between cores. The HT/SMT impact on performance can also be visualized (the plotting tool is in my `Piernik-benchmarks` repository). New data is shown on top-right panel on the attached example.
The i9-14900K consists of 8 P-cores and 16 E-cores ("performance" and "efficient", respectively). The P-cores are capable of HT with two hardware threads on each physical core while the E-cores are single-threaded. The E-cores also have lower clock and smaller amount of available L1- and L2-cache.
The P-cores are visible to the system as the processors 0 .. 15 (it translates to 1 .. 16 on the graph), remaining ones (17 .. 32) are the E-cores. 
* On such machine, first 8 threads are usually assigned by the system to …
=> [piernik_bench] add core profiling functionality for benchmark analysis

jenkins/gold_configs/MHDsedovAMR.config, src/scheme/Riemann_Solver/solve_cg_riemann.F90
care_for_positives should operate with arrays after the update: u1 and b1
=> Riemann care for positives
